name: Angular Build

# {1}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: angular-project

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: angular-project/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run prettier